### ISSUE TITLE
Review other style guides and refer to their rules

### ISSUE THREAD

**Issue by Eiji7** [lexmag/elixir-style-guide#22]
There are lots of other style guide like:
* [The Elixir Style Guide](https://github.com/christopheradams/elixir_style_guide) by @christopheradams
* [Credo's Elixir Style Guide](https://github.com/rrrene/elixir-style-guide) by @rrrene

Do you interested in comparing them and add/modify rules (of course in our own way) here?
Can I take it and create a PR's for each style guide, so we can discuss about possible changes?

**Comment by christopheradams** [comment]
There's quite a bit of overlap. It might not be a bad idea to unify the language of any rules that are the same, so that whatever differences are left are easier to see and discuss. I had the idea of adding `[credo]` links to the style guide I maintain, so people can see which rules would be enforced by a linter and which are more opinionated or meta-styles.

**Comment by whatyouhide** [comment]
Since this style guide is the one that's being used for formatters (like https://github.com/uohzxela/ex_format and https://github.com/lpil/exfmt), I would go ahead and close this issue as it's unlikely we're gonna link other style guides (or single rules) in this guide. If you want to link rules from this style guides into @christopheradams's style guide or Credo's style guide, feel free to do it 👍 Thanks all!
