### ISSUE TITLE
Parenthesizing captures

### ISSUE THREAD

**Issue by whatyouhide** [lexmag/elixir-style-guide#43]
Today there's not written rule in the style guide, but we do write captures like this:

```elixir
&not(&1 or &2)
&if(&1, do: &2, else: :default)
```

instead of how the style guide would suggest (especially for things like `not`):

```elixir
&(not (&1 or &2))
```

While I like the first version better, I think we should go with the second version for consistency. It would also make a formatter's job easier. Wdyt @lexmag and @josevalim?

**Comment by josevalim** [comment]
Let's never add parens for `&`. That's because if the inner expression needs parens, it will be parenthesized anyway. I will be glad to revisit this decision later but as a starting point, we can trust that.

**Comment by josevalim** [comment]
Actually, it is not quite as simple. That's because we want to have: `& &1` and `&foo(&1)`. Notice that one has spaces after `&` and the other does not. So we will need to make a distinction between some expressions and some others. I guess if the inner expression is a binary operator or a lone `&1` we will need to add parens.

**Comment by whatyouhide** [comment]
In that case, we can leave `if` and `not` and friends with parens, as in `&not(&1 or &2)`, which is nice 👍

**Comment by whatyouhide** [comment]
Can I close this as it's taken care of by the formatter?

**Comment by josevalim** [comment]
Yup. The formatter will add parens if you have ambiguity (aka binary operators).
